//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public decimal ARTICLE_ID { get; set; }
        public string ARTICLE_TITLE { get; set; }
        public string ARTICLE_BRIEF { get; set; }
        public string ARTICLE_CONTENT { get; set; }
        public string ARTICLE_TAGS { get; set; }
        public Nullable<bool> ARTICLE_IS_HOT { get; set; }
        public string ARTICLE_IMAGE_LARGE { get; set; }
        public string ARTICLE_IMAGE_THUMB { get; set; }
        public string ARTICLE_FILE_NAME_1 { get; set; }
        public string ARTICLE_FILE_PATH_1 { get; set; }
        public string ARTICLE_FILE_NAME_2 { get; set; }
        public string ARTICLE_FILE_PATH_2 { get; set; }
        public Nullable<int> ARTICLE_RATE_COUNT { get; set; }
        public Nullable<decimal> ARTICLE_RATE_SUM_STAR { get; set; }
        public Nullable<int> ARTICLE_VIEW_TOTAL { get; set; }
        public Nullable<System.DateTime> ARTICLE_CREATEDATE { get; set; }
        public string ARTICLE_CREATEBY { get; set; }
        public string ARTICLE_ALIAS { get; set; }
        public Nullable<bool> ARTICLE_DISABLE { get; set; }
        public Nullable<decimal> CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_ALIAS { get; set; }
        public Nullable<decimal> TITLE_TRANSLATION_ID { get; set; }
        public Nullable<decimal> BRIEF_TRANSLATION_ID { get; set; }
        public Nullable<decimal> CONTENT_TRANSLATION_ID { get; set; }
        public Nullable<decimal> NAME_TRANSLATION_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
