//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BOOKINGEntities : DbContext
    {
        public DB_BOOKINGEntities()
            : base("name=DB_BOOKINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ARTICLE> ARTICLEs { get; set; }
        public virtual DbSet<BOOKING_ROOM> BOOKING_ROOM { get; set; }
        public virtual DbSet<BOOKING_ROOM_DETAIL> BOOKING_ROOM_DETAIL { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<HITCOUTER> HITCOUTERs { get; set; }
        public virtual DbSet<HOTEL> HOTELs { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<Medium> MEDIA { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<PACKAGE_ROOM> PACKAGE_ROOM { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<ROOM_TYPE> ROOM_TYPE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRANSLATION> TRANSLATIONs { get; set; }
        public virtual DbSet<TRANSLATION_ARTICLE> TRANSLATION_ARTICLE { get; set; }
        public virtual DbSet<TRANSLATION_CATEGORY> TRANSLATION_CATEGORY { get; set; }
        public virtual DbSet<TRANSLATION_CUSTOMER> TRANSLATION_CUSTOMER { get; set; }
        public virtual DbSet<TRANSLATION_HOTEL> TRANSLATION_HOTEL { get; set; }
        public virtual DbSet<TRANSLATION_ROOM_TYPE> TRANSLATION_ROOM_TYPE { get; set; }
        public virtual DbSet<TRANSLATION_ROOM> TRANSLATION_ROOM { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
    }
}
