//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_ROOM_DETAIL
    {
        public string BOOKING_CODE { get; set; }
        public decimal ROOM_ID { get; set; }
        public string ROOM_CODE { get; set; }
        public string ROOM_NAME { get; set; }
        public Nullable<System.DateTime> DATE_BEGIN { get; set; }
        public Nullable<System.DateTime> DATE_FINISH { get; set; }
        public Nullable<short> NUMBER_NIGHT { get; set; }
        public Nullable<decimal> HOTEL_ID { get; set; }
        public string HOTEL_NAME { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public string CUSTOMER_FULLNAME { get; set; }
    
        public virtual BOOKING_ROOM BOOKING_ROOM { get; set; }
        public virtual HOTEL HOTEL { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
