//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public decimal COMMENT_ID { get; set; }
        public Nullable<decimal> FROM_ID_CUSTOMER { get; set; }
        public Nullable<decimal> TO_ID_HOTEL { get; set; }
        public string MESSEGER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<bool> COMMENT_DISABLE { get; set; }
        public Nullable<int> NUMBER_RATING { get; set; }
    }
}
