//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.BOOKING_ROOM = new HashSet<BOOKING_ROOM>();
            this.MEMBERs = new HashSet<MEMBER>();
        }
    
        public decimal CUSTOMER_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string PEOPLE_ID_NUMBER { get; set; }
        public Nullable<System.DateTime> PEOPLE_ID_ISSUE_DATE { get; set; }
        public string PEOPLE_ID_ISSUE_PLACE { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string PASSPORT_ISSUE_PLACE { get; set; }
        public Nullable<System.DateTime> PASSPORT_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> PASSPORT_EXPIRATION_DATE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<bool> IS_MEMBER { get; set; }
    
        public virtual ICollection<BOOKING_ROOM> BOOKING_ROOM { get; set; }
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
    }
}
