//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HITCOUTER
    {
        public int ID { get; set; }
        public Nullable<int> DAY_NUMBER { get; set; }
        public Nullable<int> WEEKNUMBER { get; set; }
        public Nullable<int> MONTHNUMBER { get; set; }
        public Nullable<int> TOTALNUMBER { get; set; }
        public Nullable<int> MaxOnNumber { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public Nullable<System.DateTime> MaxOnDay { get; set; }
        public Nullable<int> MaxConnection { get; set; }
    }
}
