//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public string MEMBER_USERNAME { get; set; }
        public string MEMBER_PASSWORD { get; set; }
        public Nullable<System.DateTime> MEMBER_CREATEDATE { get; set; }
        public Nullable<decimal> CUSTOMER_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> NUMBER_BOOK { get; set; }
        public decimal MEMBER_ID { get; set; }
        public Nullable<System.DateTime> LAST_DATE_VISIT { get; set; }
        public Nullable<bool> MEMBER_ACTIVE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
