//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE_ROOM
    {
        public decimal PACKAGE_ID { get; set; }
        public string PACKAGE_NAME { get; set; }
        public string PACKAGE_BRIEF { get; set; }
        public string PACKAGE_CONTENT { get; set; }
        public Nullable<System.DateTime> PACKAGE_START_DATE { get; set; }
        public Nullable<System.DateTime> PACKAGE_END_DATE { get; set; }
        public string HOTEL_NAME { get; set; }
        public string STORAGE_DATE { get; set; }
        public string STORAGE_PRICE { get; set; }
        public string STORAGE_PRICE_SELL { get; set; }
        public Nullable<int> NUMBER_ROOM { get; set; }
    }
}
