//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ACCOUNTs = new HashSet<ACCOUNT>();
            this.CATEGORies = new HashSet<CATEGORY>();
        }
    
        public decimal ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<bool> ROLE_ALLOW_ADD { get; set; }
        public Nullable<bool> ROLE_ALLOW_UPDATE { get; set; }
        public Nullable<bool> ROLE_ALLOW_DELETE { get; set; }
        public Nullable<bool> ROLE_ALLOW_VIEW { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
    }
}
