//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public ROOM()
        {
            this.BOOKING_ROOM_DETAIL = new HashSet<BOOKING_ROOM_DETAIL>();
            this.TRANSLATION_ROOM = new List<TRANSLATION_ROOM>();
        }
    
        public decimal? ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public string ROOM_CODE { get; set; }
        public string ROOM_ACREAGE { get; set; }
        public Nullable<int> NUMBER_BED { get; set; }
        public Nullable<int> ROOM_PRICE { get; set; }
        public Nullable<decimal> ROOM_TYPE_ID { get; set; }
        public Nullable<decimal> HOTEL_ID { get; set; }
        public string ROOM_IMAGE { get; set; }
        public Nullable<bool> ROOM_STATUS { get; set; }
        public string ROOM_PRICE_SELL { get; set; }
    
        public virtual ICollection<BOOKING_ROOM_DETAIL> BOOKING_ROOM_DETAIL { get; set; }
        public virtual HOTEL HOTEL { get; set; }
        public virtual ROOM_TYPE ROOM_TYPE { get; set; }
        public virtual List<TRANSLATION_ROOM> TRANSLATION_ROOM { get; set; }
    }
}
