//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ROOM_TYPE
    {
        public ROOM_TYPE()
        {
            this.ROOMs = new HashSet<ROOM>();
            this.TRANSLATION_ROOM_TYPE = new List<TRANSLATION_ROOM_TYPE>();
        }

        public decimal? ROOM_TYPE_ID { get; set; }
        [Required]
        [DisplayName("Loại Phòng")]
        [StringLength(200)]
        public string ROOM_TYPE_NAME { get; set; }
    
        public virtual ICollection<ROOM> ROOMs { get; set; }
        public virtual List<TRANSLATION_ROOM_TYPE> TRANSLATION_ROOM_TYPE { get; set; }
    }
}
