//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    
    public partial class TRANSLATION_ROOM
    {
        public decimal ID { get; set; }
        public decimal LANGUAGE_ID { get; set; }
        public string TEXT { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
=======
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TRANSLATION_ROOM
    {
        public decimal? ID { get; set; }
        [Required]
        public decimal LANGUAGE_ID { get; set; }
        [DisplayName("Tên Phòng")]
        [StringLength(200)]
        public string ROOM_NAME { get; set; }
        [Required]
        public decimal ROOM_ID { get; set; }

        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual ROOM ROOM { get; set; }
>>>>>>> refs/remotes/origin/master
    }
}
