//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSLATION_ARTICLE
    {
        public TRANSLATION_ARTICLE()
        {
            this.ARTICLEs = new HashSet<ARTICLE>();
            this.ARTICLEs1 = new HashSet<ARTICLE>();
        }
    
        public decimal ID { get; set; }
        public decimal LANGUAGE_ID { get; set; }
        public string TEXT { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLEs { get; set; }
        public virtual ICollection<ARTICLE> ARTICLEs1 { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
    }
}
